# Generated by Django 6.1 on 2026-08-13 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fipe_code', models.PositiveIntegerField(verbose_name='código FIPE')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('vehicle_type', models.PositiveSmallIntegerField(choices=[(1, 'Carro'), (2, 'Moto'), (3, 'Caminhão')], default=1, verbose_name='tipo de veículo')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('vehicle_type', 'fipe_code'), name='unique_brand_per_vehicle_type')],
            },
        ),
        migrations.CreateModel(
            name='ReferenceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fipe_code', models.PositiveIntegerField(unique=True, verbose_name='código FIPE')),
                ('month', models.PositiveSmallIntegerField(verbose_name='mês')),
                ('year', models.PositiveSmallIntegerField(verbose_name='ano')),
            ],
            options={
                'verbose_name': 'tabela de referência',
                'verbose_name_plural': 'tabelas de referência',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_reference_period')],
            },
        ),
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.PositiveSmallIntegerField(choices=[(1, 'Carro'), (2, 'Moto'), (3, 'Caminhão')], default=1, verbose_name='tipo de veículo')),
                ('status', models.CharField(choices=[('running', 'Em andamento'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='running', max_length=12, verbose_name='situação')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='iniciada em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizada em')),
                ('brands_done', models.PositiveIntegerField(default=0, verbose_name='marcas concluídas')),
                ('models_done', models.PositiveIntegerField(default=0, verbose_name='modelos concluídos')),
                ('quotes_created', models.PositiveIntegerField(default=0, verbose_name='cotações criadas')),
                ('quotes_updated', models.PositiveIntegerField(default=0, verbose_name='cotações atualizadas')),
                ('last_error', models.TextField(blank=True, verbose_name='último erro')),
                ('reference_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_runs', to='crawler.referencetable', verbose_name='tabela de referência')),
            ],
            options={
                'verbose_name': 'execução do crawler',
                'verbose_name_plural': 'execuções do crawler',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fipe_code', models.PositiveIntegerField(verbose_name='código FIPE')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='crawler.brand', verbose_name='marca')),
            ],
            options={
                'verbose_name': 'modelo',
                'verbose_name_plural': 'modelos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fipe_year_code', models.CharField(max_length=12, verbose_name='código ano FIPE')),
                ('year', models.PositiveIntegerField(verbose_name='ano')),
                ('fuel_type', models.PositiveSmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Álcool'), (3, 'Diesel')], default=1, verbose_name='combustível')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_years', to='crawler.vehiclemodel', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'ano/modelo',
                'verbose_name_plural': 'anos/modelos',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CrawlCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False, verbose_name='concluída')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.brand', verbose_name='marca')),
                ('crawl_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='crawler.crawlrun', verbose_name='execução')),
            ],
            options={
                'verbose_name': 'checkpoint',
                'verbose_name_plural': 'checkpoints',
                'constraints': [models.UniqueConstraint(fields=('crawl_run', 'brand'), name='unique_checkpoint_per_brand')],
            },
        ),
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('fipe_code', models.CharField(max_length=20, verbose_name='código FIPE')),
                ('collected_at', models.DateTimeField(auto_now=True, verbose_name='coletado em')),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='crawler.modelyear', verbose_name='ano/modelo')),
                ('reference_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='crawler.referencetable', verbose_name='tabela de referência')),
            ],
            options={
                'verbose_name': 'cotação',
                'verbose_name_plural': 'cotações',
                'ordering': ['-reference_table__year', '-reference_table__month'],
                'indexes': [models.Index(fields=['model_year', 'reference_table'], name='quote_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('model_year', 'reference_table'), name='unique_quote_per_reference')],
            },
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'fipe_code'), name='unique_model_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='modelyear',
            constraint=models.UniqueConstraint(fields=('vehicle_model', 'fipe_year_code'), name='unique_year_per_model'),
        ),
    ]
