# Generated by Django 6.1 on 2026-08-13 02:38

from django.db import migrations, models


def copy_fuel_from_model_year(apps, schema_editor):
    """Existing quotes would all default to gasoline; take the real value.

    Driven by the fuel codes actually present, because FIPE uses more of them
    than the enum knew when this migration was written (4 = elétrico, 5 = flex).
    """
    PriceQuote = apps.get_model('crawler', 'PriceQuote')
    ModelYear = apps.get_model('crawler', 'ModelYear')
    known = ModelYear.objects.exclude(fuel_type=1).values_list('fuel_type', flat=True).distinct()
    for fuel_type in known:
        PriceQuote.objects.filter(
            fuel_type=1, model_year__fuel_type=fuel_type
        ).update(fuel_type=fuel_type)


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricequote',
            name='fuel_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Álcool'), (3, 'Diesel')], default=1, verbose_name='combustível'),
        ),
        migrations.RunPython(copy_fuel_from_model_year, migrations.RunPython.noop),
    ]
