# Generated by Django 6.1 on 2026-08-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_backfill_quote_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelyear',
            name='fuel_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Álcool'), (3, 'Diesel'), (4, 'Elétrico'), (5, 'Flex')], default=1, verbose_name='combustível'),
        ),
        migrations.AlterField(
            model_name='pricequote',
            name='fuel_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Álcool'), (3, 'Diesel'), (4, 'Elétrico'), (5, 'Flex')], default=1, verbose_name='combustível'),
        ),
    ]
