# Generated by Django 6.1 on 2026-08-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_modelyear_fuel_type_alter_pricequote_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelyear',
            name='fuel_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Álcool'), (3, 'Diesel'), (4, 'Elétrico'), (5, 'Flex'), (6, 'Híbrido'), (7, 'Tetrafuel')], default=1, verbose_name='combustível'),
        ),
        migrations.AlterField(
            model_name='pricequote',
            name='fuel_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Álcool'), (3, 'Diesel'), (4, 'Elétrico'), (5, 'Flex'), (6, 'Híbrido'), (7, 'Tetrafuel')], default=1, verbose_name='combustível'),
        ),
    ]
