# Generated by Django 6.1 on 2026-08-13 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_alter_modelyear_fuel_type_alter_pricequote_fuel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='relevância')),
                ('status', models.CharField(choices=[('pending', 'Agendada'), ('running', 'Em andamento'), ('partial', 'Parcial'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=12, verbose_name='situação')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizado em')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.vehiclemodel', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'item de coleta',
                'verbose_name_plural': 'itens de coleta',
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='termo buscado')),
                ('vehicle_type', models.PositiveSmallIntegerField(choices=[(1, 'Carro'), (2, 'Moto'), (3, 'Caminhão')], default=1, verbose_name='tipo de veículo')),
                ('status', models.CharField(choices=[('pending', 'Agendada'), ('running', 'Em andamento'), ('partial', 'Parcial'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=12, verbose_name='situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizada em')),
                ('models_done', models.PositiveIntegerField(default=0, verbose_name='modelos concluídos')),
                ('quotes_created', models.PositiveIntegerField(default=0, verbose_name='cotações criadas')),
                ('quotes_updated', models.PositiveIntegerField(default=0, verbose_name='cotações atualizadas')),
                ('quotes_missing', models.PositiveIntegerField(default=0, verbose_name='sem cotação na FIPE')),
                ('requests_spent', models.PositiveIntegerField(default=0, verbose_name='requisições gastas')),
                ('last_error', models.TextField(blank=True, verbose_name='último erro')),
                ('vehicle_models', models.ManyToManyField(related_name='collection_requests', through='crawler.CollectionItem', to='crawler.vehiclemodel', verbose_name='modelos')),
            ],
            options={
                'verbose_name': 'coleta sob demanda',
                'verbose_name_plural': 'coletas sob demanda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crawler.collectionrequest', verbose_name='coleta'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('request', 'vehicle_model'), name='unique_model_per_collection'),
        ),
    ]
