# Generated by Django 6.1 on 2026-08-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_collection_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Criada'), (2, 'Atualizada'), (3, 'Sem cotação')], default=1, verbose_name='situação')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='consultado em')),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookups', to='crawler.modelyear', verbose_name='ano/modelo')),
                ('reference_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookups', to='crawler.referencetable', verbose_name='tabela de referência')),
            ],
            options={
                'verbose_name': 'consulta de cotação',
                'verbose_name_plural': 'consultas de cotação',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['reference_table', 'status'], name='lookup_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('model_year', 'reference_table'), name='unique_lookup_per_reference')],
            },
        ),
    ]
