# Generated by Django 6.1 on 2026-08-17 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_quotelookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=3, unique=True, verbose_name='valor')),
                ('description', models.CharField(max_length=30, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'tipo de motor',
                'verbose_name_plural': 'tipos de motor',
                'ordering': ['value'],
            },
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='engine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='crawler.enginetype', verbose_name='tipo de motor'),
        ),
    ]
